### ISSUE TITLE
Prepend vs. Append of CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by peter-lehner** [ros/cmake_modules#21]
In both
https://github.com/ros/cmake_modules/blob/0.3-devel/cmake/cmake_modules-extras.cmake.develspace.in#L2
and
https://github.com/ros/cmake_modules/blob/0.3-devel/cmake/cmake_modules-extras.cmake.installspace.in#L2
you prepend your own modules to the CMAKE_MODULE_PATH. This has the disadvantage that I cannot prepend my own FindPACKAGE.cmake paths and thereby replace your FindPACKAGE.cmake files with my own. I need to replace your FindPACKAGE.cmake files by my own because the customization via PACKAGE_ROOT_DIR is not enough as I have my libraries in architecture (32/64 bit) dependent subdirectories. Additionally this solution would safe me the work of specifying each PACKAGE_ROOT_DIR manually.

What would be the disadvantages of appending your modules to the CMAKE_MODULE_PATH? As I see it all the provided find scripts are for libraries which are not included in standard cmake anyways.

**Comment by wjwwood** [comment]
I can't think of a reason for having it be prepend off the top of my head, but I vaguely remember needing it to be this way to support some case. @dirk-thomas @adolfo-rt can either of you think of a scenario where append would not work where prepend does?

If we cannot think of a reason to not use append, I think we can change it, but out of curiosity can you not work around this by simply prepending your own path to the CMAKE_MODULE_PATH after calling `find_package(...)` on this package? Something like this:

``` cmake
find_package(cmake_modules REQUIRED)

list(INSERT CMAKE_MODULE_PATH 0 "my_cmake/Modules")

find_package(...)  # now find stuff with your modules
```

**Comment by dirk-thomas** [comment]
Since the module path is empty by default I can't think of any case where append would make a difference.

**Comment by peter-lehner** [comment]
> but out of curiosity can you not work around this by simply prepending your own path to the CMAKE_MODULE_PATH after calling find_package(...) on this package?

Yes, I could definitly do this for my own downstream packages. The problem lies in downstream packages of third authors, for example rospack (https://github.com/ros/rospack/blob/indigo-devel/CMakeLists.txt), which I would rather not patch individually for my setup.

**Comment by wjwwood** [comment]
If you need to affect how rospack finds something that this package provides the CMake Module for, then you should have a workspace with a modified version of this package.

Either way, I don't see why we cannot change the prepend to an append. @peter-lehner can you open a pull request to that affect? It would save me some time, get it done more quickly and give you attribution.

Thanks.

**Comment by peter-lehner** [comment]
Okay, I opened the pull request. This is the first pull request I created, so please check I did everything correctly. Thank you!

**Comment by adolfo-rt** [comment]
+1 for appending

If the pattern is to be able to call

``` cmake
find_package(cmake_modules REQUIRED)
```

yet allow to manually override a particular module path before or after the above call, appending is the way to go.
