### ISSUE TITLE
Problem using GSL

### ISSUE THREAD

**Issue by astrame** [ros/cmake_modules#27]
Hi,

I stumbled upon this catkin package while trying to use GSL library in my ros node in Hydro. I did the following:
1. Downloaded the package to catkin src/ folder
2. Added <build_depend>cmake_modules</build_depend> in package.xml in the node in which I want to use GSL
3. Added find_package(catkin REQUIRED COMPONENTS ... cmake_modules ...) in CMakeLists.txt
4. Added find_package(GSL REQUIRED) in CMakeLists.txt

When I do catkin_make I get the following error

 PKGCONFIG() indicates that gsl is not installed (install the package which contains gsl.pc if you want to support this feature)
FindGSL.cmake: gsl-config/pkg-config gsl not found. Please set it manually. GSL_CONFIG=GSL_CONFIG-NOTFOUND
CMake Error at cmake_modules/cmake/Modules/FindGSL.cmake:173 (MESSAGE):
  GSL required, please specify it's location.

Is GSL not included in this package ? What am I missing. Sorry if the question is very basic.

Thanks.

**Comment by astrame** [comment]
Ok, so I found the issue. I had installed GSL using:  sudo apt-get install libgsl0ldbl  on terminal
I needed to use: apt-get install gsl-bin libgsl0-dev

I still have one more problem. I was trying to use gsl_ran_gaussian function and I get the following error:

 undefined reference to `gsl_ran_gaussian'

I am not sure how to solve this problem.

**Comment by astrame** [comment]
Solved the problem by adding this lines in the CMakeLists.txt

target_link_libraries(Motion_features ${GSL_LIBRARIES} )

**Comment by wjwwood** [comment]
Yeah, so the first problem you had was that this package only contains the CMake stuff to _find_ GSL, not GSL itself, so you solved that by installing GSL.

The second problem was that you were using a function from a header in GSL but not linking against it, which is indeed solved by using `target_link_libraries(...)` to link against it.

I'm gonna close this.

**Comment by astrame** [comment]
yes Thank you.
