### ISSUE TITLE
Add gflags module

### ISSUE THREAD

**Issue by davetcoleman** [ros/cmake_modules#36]
I don't know a ton about CMake modules, but I found this module and it works in my project for bringing in gflags. Think we could add it to this repo instead of having it locally in mine?

https://github.com/exuvo/kbot/blob/f6fbb7c5f50774f64dc350c06ca487dfd6a0e850/kbot_bridge/cmake/FindGflags.cmake

**Comment by wjwwood** [comment]
Just doing a quick search, it looks like `gflags` provides a CMake config file:

http://gflags.github.io/gflags/#cmake

Does their suggested way of using gflags in cmake not work for you?

**Comment by davetcoleman** [comment]
I looked at that page, yes, but it did not seem to work. I just added

```
   find_package(gflags REQUIRED)
```

Not sure what else to do. But the module from the above link did work when I explicitly added:

```
set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)
```

**Comment by wjwwood** [comment]
I'm hesitant to add a CMake module here until it's clear that the upstream package doesn't provide one or that it is broken on one or more systems to which we deploy. If you're on Ubuntu can you post the output of `dpkg --listfiles gflags`? Also include what version of ROS and OS you're using.

**Comment by davetcoleman** [comment]
There are no flags for gflags. However, for more exact names:

dpkg --listfiles libgflags-dev

```
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libgflags_nothreads.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libgflags.pc
/usr/lib/x86_64-linux-gnu/libgflags_nothreads.a
/usr/lib/x86_64-linux-gnu/libgflags.a
/usr/share
/usr/share/doc
/usr/share/doc/libgflags-dev
/usr/share/doc/libgflags-dev/copyright
/usr/include
/usr/include/google
/usr/include/google/gflags.h
/usr/include/google/gflags_completions.h
/usr/include/gflags
/usr/include/gflags/gflags.h
/usr/include/gflags/gflags_completions.h
/usr/include/gflags/gflags_declare.h
/usr/lib/x86_64-linux-gnu/libgflags_nothreads.so
/usr/lib/x86_64-linux-gnu/libgflags.so
/usr/share/doc/libgflags-dev/changelog.Debian.gz
```

dpkg --listfiles libgflags2

```
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgflags.so.2.1.0
/usr/lib/x86_64-linux-gnu/libgflags_nothreads.so.2.1.0
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libgflags2
/usr/share/doc
/usr/share/doc/libgflags2
/usr/share/doc/libgflags2/copyright
/usr/share/doc/libgflags2/changelog.Debian.gz
/usr/lib/x86_64-linux-gnu/libgflags_nothreads.so.2
/usr/lib/x86_64-linux-gnu/libgflags.so.2
```

No cmake files found...

**Comment by davetcoleman** [comment]
Note that I'm proposing we use another ROS user's gflags solution: https://github.com/exuvo/kbot/

**Comment by wjwwood** [comment]
That's strange, as of 2.1.0 it should have CMake config files:

https://github.com/gflags/gflags#20-march-2014

And it looks like you've got 2.1.0 there, so it must be a bug in the debian/ubuntu packaging. So it makes sense to me for a gflags module to be here, but looking over the module you linked to it find the files manually by searching. I think it would be better to use pkg-config inside the CMake module. I can see that libgflags-dev installs pkg-config files:

```
...
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libgflags_nothreads.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libgflags.pc
...
```

But that's an optional optimization I guess. I'd review a pull request which either finds the files manually or uses pkg-config. Be sure to have a look at this repositories contribution guidelines if you (or anyone else) is going to do that:

https://github.com/ros/cmake_modules/blob/0.4-devel/CONTRIBUTING.md

**Comment by davetcoleman** [comment]
Never mind, this looks more complicated than just dropping a file into cmake_modules - I don't want to get too involved in this, I was just playing with gflags for the first time because it seems like a common tool.

**Comment by schuhschuh** [comment]
The CMake configuration file provided by gflags 2.1 should work perfectly fine and if there are issues with the gflags-config.cmake file provided by the package, please report it and I have a look. A pkg-config file is not needed.

As @wjwwood noted, this is more likely a problem of the Debian/Ubuntu package. Even though it suggests to contain gflags version 2.1, it's more likely version 2.0 given the list of files which was still using the auto tools for the build and installation. Or, the package maintainer decided to use the new source files with the old packaging tools. This, however, seems unreasonable given that there are no particular code changes besides the transition to CMake between these versions.

**Comment by davetcoleman** [comment]
I've been using gflags with ROS a lot since closing this issue. I think we should just include the FindGflags module to compensate for the lack of support in Ubuntu 14.04

**Comment by davetcoleman** [comment]
@wjwwood could you look at @schuhschuh conclusion in [this comment](https://github.com/gflags/gflags/issues/120#issuecomment-130764645). I'd like to again try to move forward with adding the FindGFlags.cmake, though I would need help cleaning it up however ROS requires it.

**Comment by wjwwood** [comment]
@davetcoleman sorry it has taken me so long to get back on this. I'm fine to add GFlags to this repository since it appears to be necessary.

However, this should be a temporary arrangement if possible, see: https://github.com/ros/cmake_modules/blob/0.4-devel/CONTRIBUTING.md#long-term-contribution

@schuhschuh is there anything else we should do to ensure that the proper configuration files are distributed with future Ubuntu versions?

@davetcoleman please open a pull request and I'll help you get it merged. Be sure to add the necessary comments in the top of the file as described in our contribution file: https://github.com/ros/cmake_modules/blob/0.4-devel/CONTRIBUTING.md#cmake-module-style

Thanks.

**Comment by davetcoleman** [comment]
I gave it a stab just now, it works but probably needs polish. I don't understand all of it.

**Comment by davetcoleman** [comment]
Ping - now (right after the ROS release) would be a good time to release this package, right?

**Comment by schuhschuh** [comment]
BTW I would suggest to extend the originally linked `FindGflags.cmake` module. The Ubuntu package contains a package config file that CMake can use. Check out the [CMake sample Find module](https://cmake.org/cmake/help/v3.4/manual/cmake-developer.7.html#a-sample-find-module) as to how. Maybe:

``` cmake
find_package(PkgConfig)
pkg_check_modules(PC_gflags QUIET libgflags)
```

**Comment by davetcoleman** [comment]
Thanks for your suggestion, you are probably right that would be an improvement. Since this module might not ever be released into indigo, I've had to give up on using cmake_modules for this and have my own workarounds. I'd like to retract my interest in working on this config file, we could even revert the commit if desired.
