### ISSUE TITLE
libtinyxml2-4.0.1 is having regression, rospack not working correctly

### ISSUE THREAD

**Issue by justdoGIT** [ros/cmake_modules#46]
rospack is facing issues on armhf debian stretch due to  libtinyxml2-4.0.1 see this for more details [https://answers.ros.org/question/278733/rospack-find-throws-exception-error/](url). Can someone suggest me some patches or other work around to solve the issue.

**Comment by dirk-thomas** [comment]
Please do not double/triple post your question which you have also asked on answers.ros.org and ros/rospack#77.

**Comment by wjwwood** [comment]
Also, this repository only helps find things like tinyxml2, it doesn't provide them so it cannot be the place to fix the issue you're describing.

As for asking in multiple places, which @dirk-thomas mentioned, that is considered poor etiquette, see http://wiki.ros.org/Support#Etiquette

**Comment by mikaelarguedas** [comment]
@kamalpandey1993 see https://github.com/ros/rospack/issues/77#issuecomment-356619084
