### ISSUE TITLE
FindPoco doesn't validate presence of Debug libraries in Debug configuration

### ISSUE THREAD

**Issue by nuclearsandwich** [ros/cmake_modules#49]
Passing on a bug reported in https://github.com/ros/class_loader/issues/117

When running with `CMAKE_BUILD_TYPE=Debug` `Poco_LIBRARIES` is set to `dl` which causes linking issues at runtime.

I can demonstrate the issue with this cmake project on Ubuntu 18.04.

```
cmake_minimum_required(VERSION 3.5)
project(test_poco CXX)

find_package(catkin REQUIRED COMPONENTS cmake_modules)
find_package(Poco REQUIRED COMPONENTS Foundation)
message(STATUS "Poco_LIBRARIES ${Poco_LIBRARIES}")
```

```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
-- Using CATKIN_DEVEL_PREFIX: /tmp/ws/src/class_loader/test_poco/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/ws/src/class_loader/test_poco/build/test_results
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- Searching for Poco library...
--   Found Poco!
-- components found: Foundationd.
-- Poco_LIBRARIES dl
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ws/src/class_loader/test_poco/build
```

Commenting out `find_package(catkin COMPONENTS cmake_modules)` on the same system uses cmake modules provided by the libpoco-dev debian package to work as (somewhat) expected in that it yields the regular poco foundation shared object. I don't see any debug versions of poco packaged in Debian or Ubuntu but I may be looking in the wrong place.

**Comment by nuclearsandwich** [comment]
I figured out what's going on here and opened #50 to resolve it.

**Comment by jspricke** [comment]
@nuclearsandwich 
debug symbols are in the respective repos:
https://wiki.debian.org/HowToGetABacktrace
https://wiki.ubuntu.com/Debug%20Symbol%20Packages
