### ISSUE TITLE
avoid using absolute paths in generate CMake extra file

### ISSUE THREAD

**Issue by dirk-thomas** [ros/cmake_modules#9]
Instead of using the `CMAKE_INSTALL_PREFIX` in https://github.com/ros/cmake_modules/blob/master/cmake/cmake_modules-extras.cmake.develspace.in#L2 the `Modules` folder should be resolved relatively to `${cmake_modules_DIR}` (e.g. like https://github.com/ros/gencpp/blob/hydro-devel/cmake/gencpp-extras.cmake.em).

**Comment by wjwwood** [comment]
You mean like this line?: https://github.com/ros/gencpp/blob/hydro-devel/cmake/gencpp-extras.cmake.em#L7

**Comment by dirk-thomas** [comment]
Yes, but you willl still need the conditional block to deal with the devel space.
